# Entrega 1
- Descripción del sistema computacional:
- Pregunta de estudio: 
- Tipos de datos a recolectar:

# Entrega 2
- Metodología de evaluación de desempeño:
    (Monitoreo, benchmarking o redes de colas)
- Diseño del estudio (y primeros resultados):

# Entrega 3
Informe final con
- Recoleccion de Datos
- Resultados
> con interpretacion
- Conclusiones

$$\text{Lista Nueva lista de Data}$$

<img src="newData/list.png" alt="Girl in a jacket">

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
def readData(filename, sep=",", parse_dates=[]):
    data = pd.read_csv(filename, sep=sep)    
    for col in parse_dates:
        data[col] = pd.to_datetime(data[col], errors="coerce")
    return data   
    
def hCumsum(data):
    columns = data.columns[1:]
    data[columns] = data[columns].cumsum(axis=1)
    return data, columns

In [7]:
# 1. Read and clean data

# 1.1 WebData
'''
archivos = [
    "CPU Utilization.csv", #0
    "GPU Utilization.csv", #1
    "GPU Used Memory.csv", #2
    "Memory.csv",          #3
    "Patagon - Power.csv", #4
]

data = []
cols_ix = [] 
for i, a in enumerate(archivos):
    d, c = hCumsum(readData(a, parse_dates=["Time"]))
    data.append(d)
    cols_ix.append(c)
'''

# 1.2 PatagonData
monitoreo = readData("../Shared/monitoreo.csv", sep="|", parse_dates=['Start', 'End'])

##### Cantidad de Nulls por data (donde hayan)
Universo: 15412
- "Unnamed: 19": todos jj
- "MinCPU": 924
- "MaxVMSize": 924
- "AveVMSize"
- "MaxRSS": 924
- "AveRSS": 924
- "MaxDiskWrite": 924
- "AveDiskWrite": 924
- "MaxDiskRead": 924
- "AveDiskRead": 924
- "ReqTRES": 10364

In [8]:
filtrado = [
    'Unnamed: 19'
]

In [9]:
filtered_monitoreo = monitoreo.copy()
filtered_monitoreo.drop(filtrado, axis=1, inplace=True)
print(len(filtered_monitoreo))

15412

In [10]:
display(filtered_monitoreo)

,State,Start,End,Elapsed,ReqMem,ReqTRES,AveDiskRead,MaxDiskRead,AveDiskWrite,MaxDiskWrite,AveRSS,MaxRSS,AveVMSize,MaxVMSize,ReqCPUS,CPUTime,CPUTimeRAW,MinCPU,TotalCPU
0,FAILED,2021-02-24 02:53:33,NaT,131-14:52:22,1Mn,"billing=1,cpu=1,node=1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,131-14:52:22,11371942,NaN,00:00:00
1,COMPLETED,2021-02-24 02:53:37,NaT,131-14:52:18,1Mn,"billing=1,cpu=1,node=1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,131-14:52:18,11371938,NaN,00:00:00
2,COMPLETED,2021-02-24 02:53:53,NaT,131-14:52:02,1Mn,"billing=1,cpu=1,node=1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,131-14:52:02,11371922,NaN,00:00:00
3,FAILED,2021-05-01 16:30:15,2021-05-01 16:30:16,00:00:01,100000Mn,"billing=32,cpu=32,mem=100000M,node=1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32,00:00:32,32,NaN,00:00.017
4,FAILED,2021-05-01 16:30:15,2021-05-01 16:30:16,00:00:01,100000Mn,NaN,0,0,0,0,1260K,1260K,207696K,207696K,32,00:00:32,32,00:00:00,00:00.014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15407,FAILED,2021-07-05 09:33:11,2021-07-05 09:33:12,00:00:01,0n,NaN,0,0,0,0,864K,864K,273752K,273752K,8,00:00:08,8,00:00:00,00:00.004
15408,COMPLETED,2021-07-05 09:33:12,2021-07-05 09:33:14,00:00:02,0n,NaN,0,0,0,0,856K,856K,273752K,273752K,8,00:00:16,16,00:00:00,00:00.821
15409,COMPLETED,2021-07-05 09:33:14,2021-07-05 09:33:15,00:00:01,0n,NaN,0,0,0,0,860K,860K,273752K,273752K,8,00:00:08,8,00:00:00,00:00.776
15410,RUNNING,2021-07-05 09:33:15,NaT,07:12:40,0n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8,2-09:41:20,207680,NaN,00:00:00
15411,FAILED,2021-07-05 16:45:48,2021-07-05 16:45:48,00:00:00,65556Mn,"billing=1,cpu=1,mem=65556M,node=1",0,0,0,0,840K,840K,273748K,273748K,1,00:00:00,0,00:00:00,00:00.004

In [11]:
validTime_data = filtered_monitoreo[filtered_monitoreo["Start"].notnull()]
validTime_data = filtered_monitoreo[filtered_monitoreo["End"].notnull()]
validTime_data

,State,Start,End,Elapsed,ReqMem,ReqTRES,AveDiskRead,MaxDiskRead,AveDiskWrite,MaxDiskWrite,AveRSS,MaxRSS,AveVMSize,MaxVMSize,ReqCPUS,CPUTime,CPUTimeRAW,MinCPU,TotalCPU
3,FAILED,2021-05-01 16:30:15,2021-05-01 16:30:16,00:00:01,100000Mn,"billing=32,cpu=32,mem=100000M,node=1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32,00:00:32,32,NaN,00:00.017
4,FAILED,2021-05-01 16:30:15,2021-05-01 16:30:16,00:00:01,100000Mn,NaN,0,0,0,0,1260K,1260K,207696K,207696K,32,00:00:32,32,00:00:00,00:00.014
5,FAILED,2021-05-01 16:30:15,2021-05-01 16:30:16,00:00:01,100000Mn,NaN,0,0,0,0,816K,816K,273752K,273752K,32,00:00:32,32,00:00:00,00:00.002
6,FAILED,2021-05-01 16:34:16,2021-05-01 16:34:17,00:00:01,100000Mn,"billing=32,cpu=32,mem=100000M,node=1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32,00:00:32,32,NaN,00:00.016
7,FAILED,2021-05-01 16:34:16,2021-05-01 16:34:17,00:00:01,100000Mn,NaN,0,0,0,0,1264K,1264K,207696K,207696K,32,00:00:32,32,00:00:00,00:00.013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15404,CANCELLED by 10001,2021-07-05 03:12:42,2021-07-05 03:12:42,00:00:00,65556Mn,"billing=1,cpu=1,gres/gpu=7,mem=65556M,node=1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,00:00:00,0,NaN,00:00:00
15407,FAILED,2021-07-05 09:33:11,2021-07-05 09:33:12,00:00:01,0n,NaN,0,0,0,0,864K,864K,273752K,273752K,8,00:00:08,8,00:00:00,00:00.004
15408,COMPLETED,2021-07-05 09:33:12,2021-07-05 09:33:14,00:00:02,0n,NaN,0,0,0,0,856K,856K,273752K,273752K,8,00:00:16,16,00:00:00,00:00.821
15409,COMPLETED,2021-07-05 09:33:14,2021-07-05 09:33:15,00:00:01,0n,NaN,0,0,0,0,860K,860K,273752K,273752K,8,00:00:08,8,00:00:00,00:00.776
15411,FAILED,2021-07-05 16:45:48,2021-07-05 16:45:48,00:00:00,65556Mn,"billing=1,cpu=1,mem=65556M,node=1",0,0,0,0,840K,840K,273748K,273748K,1,00:00:00,0,00:00:00,00:00.004

In [26]:
parsed_elapsed = pd.to_timedelta(validTime_data["Elapsed"], unit="S", errors="coerce")
validTime_data["Elapsed"] = parsed_elapsed

/home/santasy/.local/lib/python3.8/site-packages/pandas/core/indexing.py:1700: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, v, pi)

In [ ]:
for i in range(len(data)):
    plt.figure(figsize=(15, 10))
    plt.plot(data[i]["Time"], data[i][cols_ix[i]])
    plt.savefig("{}.png".format(archivos[i]), bbox_inches='tight')